export const CONTACT_CREATE_REQUEST = 'CONTACT_CREATE_REQUEST';
export const CONTACT_CREATE_SUCCESS = 'CONTACT_CREATE_SUCCESS';
export const CONTACT_CREATE_FAIL = 'CONTACT_CREATE_FAIL';
export const CONTACT_CREATE_RESET = 'CONTACT_CREATE_RESET';

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST';
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS';
export const CONTACT_DETAILS_FAIL = 'CONTACT_DETAILS_FAIL';

export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';

export const CONTACT_TRASH_LIST_REQUEST = 'CONTACT_TRASH_LIST_REQUEST';
export const CONTACT_TRASH_LIST_SUCCESS = 'CONTACT_TRASH_LIST_SUCCESS';
export const CONTACT_TRASH_LIST_FAIL = 'CONTACT_TRASH_LIST_FAIL';

export const CONTACT_REPLY_REQUEST = 'CONTACT_REPLY_REQUEST';
export const CONTACT_REPLY_SUCCESS = 'CONTACT_REPLY_SUCCESS';
export const CONTACT_REPLY_FAIL = 'CONTACT_REPLY_FAIL';
